export const STARTER_CATEGORIES = [
  { name: 'Salário', kind: 'INCOME' },
  { name: 'Freelance', kind: 'INCOME' },
  { name: 'Rendimentos', kind: 'INCOME' },
  { name: 'Reembolsos', kind: 'INCOME' },
  { name: 'Presentes recebidos', kind: 'INCOME' },
  { name: 'Outras receitas', kind: 'INCOME' },
  { name: 'Mercado', kind: 'EXPENSE' },
  { name: 'Alimentação', kind: 'EXPENSE' },
  { name: 'Restaurantes e delivery', kind: 'EXPENSE' },
  { name: 'Moradia', kind: 'EXPENSE' },
  { name: 'Contas da casa', kind: 'EXPENSE' },
  { name: 'Transporte', kind: 'EXPENSE' },
  { name: 'Combustível', kind: 'EXPENSE' },
  { name: 'Saúde', kind: 'EXPENSE' },
  { name: 'Farmácia', kind: 'EXPENSE' },
  { name: 'Educação', kind: 'EXPENSE' },
  { name: 'Lazer', kind: 'EXPENSE' },
  { name: 'Viagens', kind: 'EXPENSE' },
  { name: 'Compras', kind: 'EXPENSE' },
  { name: 'Vestuário', kind: 'EXPENSE' },
  { name: 'Beleza e cuidados', kind: 'EXPENSE' },
  { name: 'Assinaturas', kind: 'EXPENSE' },
  { name: 'Pets', kind: 'EXPENSE' },
  { name: 'Presentes', kind: 'EXPENSE' },
  { name: 'Seguros', kind: 'EXPENSE' },
  { name: 'Impostos e taxas', kind: 'EXPENSE' },
  { name: 'Tarifas bancárias', kind: 'EXPENSE' },
  { name: 'Doações', kind: 'EXPENSE' },
  { name: 'Outros', kind: 'EXPENSE' },
] as const;
