export type LedgerType =
  | 'INCOME'
  | 'EXPENSE'
  | 'TRANSFER'
  | 'INVESTMENT'
  | 'REDEMPTION'
  | 'CARD_PAYMENT';

export type LedgerStatus = 'POSTED' | 'PENDING' | 'CANCELED';

export type LedgerEntry = {
  type: LedgerType;
  /** Null for credit card purchases: they live on the card, not on an account. */
  accountId: string | null;
  destinationAccountId: string | null;
  amount: bigint;
  date: string;
  categoryId?: string | null;
  status?: LedgerStatus;
  /** Card purchases and card payments. */
  cardId?: string | null;
  /** YYYY-MM of the card invoice. Card expenses count in this month. */
  invoiceMonth?: string | null;
  /** Generated by a recurring rule: a fixed cost. */
  recurring?: boolean;
  installmentCount?: number | null;
};

/** Pending and canceled entries never move money. */
function effective(entry: LedgerEntry): boolean {
  return (entry.status ?? 'POSTED') === 'POSTED';
}

/** Month an entry counts toward in income/expense reports. */
export function competenceMonth(entry: LedgerEntry): string {
  if (entry.cardId && entry.type === 'EXPENSE' && entry.invoiceMonth) {
    return entry.invoiceMonth;
  }
  return entry.date.slice(0, 7);
}

export function balanceOf(accountId: string, entries: LedgerEntry[]): bigint {
  let balance = 0n;

  for (const entry of entries) {
    if (!effective(entry)) {
      continue;
    }
    if (entry.type === 'INCOME' && entry.accountId === accountId) {
      balance += entry.amount;
    }
    if (entry.type === 'EXPENSE' && entry.accountId === accountId) {
      balance -= entry.amount;
    }
    if (entry.type === 'TRANSFER' && entry.accountId === accountId) {
      balance -= entry.amount;
    }
    if (entry.type === 'TRANSFER' && entry.destinationAccountId === accountId) {
      balance += entry.amount;
    }
    if (entry.type === 'CARD_PAYMENT' && entry.accountId === accountId) {
      balance -= entry.amount;
    }
    // Contributions leave the account for an investment and redemptions
    // come back: money changes place, net worth does not.
    if (entry.type === 'INVESTMENT' && entry.accountId === accountId) {
      balance -= entry.amount;
    }
    if (entry.type === 'REDEMPTION' && entry.accountId === accountId) {
      balance += entry.amount;
    }
  }

  return balance;
}

/**
 * What is still owed on a card: every purchase installment (future ones
 * included, the purchase already happened) minus what was paid.
 */
export function cardDebt(cardId: string, entries: LedgerEntry[]): bigint {
  let debt = 0n;
  for (const entry of entries) {
    if (!effective(entry) || entry.cardId !== cardId) {
      continue;
    }
    if (entry.type === 'EXPENSE') {
      debt += entry.amount;
    }
    if (entry.type === 'CARD_PAYMENT') {
      debt -= entry.amount;
    }
  }
  return debt;
}

/**
 * Assets minus liabilities: every account (opening balance plus entries),
 * plus investments, minus card debt. Transfers, card payments,
 * contributions and redemptions cancel out.
 */
export function netWorth(
  accounts: { id: string; openingBalance: bigint }[],
  entries: LedgerEntry[],
  investments = 0n,
): bigint {
  let total = investments;
  for (const account of accounts) {
    total += account.openingBalance + balanceOf(account.id, entries);
  }
  const cards = new Set<string>();
  for (const entry of entries) {
    if (entry.cardId) {
      cards.add(entry.cardId);
    }
  }
  for (const cardId of cards) {
    total -= cardDebt(cardId, entries);
  }
  return total;
}

/** Sum of account balances only: money the user can actually spend now. */
export function availableCash(
  accounts: { id: string; openingBalance: bigint }[],
  entries: LedgerEntry[],
): bigint {
  let total = 0n;
  for (const account of accounts) {
    total += account.openingBalance + balanceOf(account.id, entries);
  }
  return total;
}

export function monthIncomeAndExpense(
  entries: LedgerEntry[],
  month: string,
): { income: bigint; expense: bigint } {
  let income = 0n;
  let expense = 0n;

  for (const entry of entries) {
    if (!effective(entry) || competenceMonth(entry) !== month) {
      continue;
    }
    if (entry.type === 'INCOME') {
      income += entry.amount;
    }
    if (entry.type === 'EXPENSE') {
      expense += entry.amount;
    }
  }

  return { income, expense };
}

/**
 * Expenses of the month grouped by category, largest first.
 * Transfers, card payments and investments are not consumption.
 */
export function monthExpenseByCategory(
  entries: LedgerEntry[],
  month: string,
): { categoryId: string | null; amount: bigint }[] {
  const totals = new Map<string | null, bigint>();

  for (const entry of entries) {
    if (
      entry.type !== 'EXPENSE' ||
      !effective(entry) ||
      competenceMonth(entry) !== month
    ) {
      continue;
    }
    const key = entry.categoryId ?? null;
    totals.set(key, (totals.get(key) ?? 0n) + entry.amount);
  }

  return [...totals.entries()]
    .map(([categoryId, amount]) => ({ categoryId, amount }))
    .sort((a, b) => (a.amount === b.amount ? 0 : a.amount > b.amount ? -1 : 1));
}

/** Total billed and paid on one invoice of one card. */
export function invoiceTotals(
  cardId: string,
  invoiceMonth: string,
  entries: LedgerEntry[],
): { total: bigint; paid: bigint } {
  let total = 0n;
  let paid = 0n;
  for (const entry of entries) {
    if (
      !effective(entry) ||
      entry.cardId !== cardId ||
      entry.invoiceMonth !== invoiceMonth
    ) {
      continue;
    }
    if (entry.type === 'EXPENSE') {
      total += entry.amount;
    }
    if (entry.type === 'CARD_PAYMENT') {
      paid += entry.amount;
    }
  }
  return { total, paid };
}

/** Entries that had happened by the end of `date` (inclusive). */
export function entriesUntil(
  entries: LedgerEntry[],
  date: string,
): LedgerEntry[] {
  return entries.filter((entry) => entry.date <= date);
}

/** Net money put into investments in a month (contributions − redemptions). */
export function monthInvested(entries: LedgerEntry[], month: string): bigint {
  let total = 0n;
  for (const entry of entries) {
    if (!effective(entry) || !entry.date.startsWith(month)) {
      continue;
    }
    if (entry.type === 'INVESTMENT') {
      total += entry.amount;
    }
    if (entry.type === 'REDEMPTION') {
      total -= entry.amount;
    }
  }
  return total;
}

/**
 * Month expenses split by nature: installments (anything paid in more than
 * one part), fixed (from recurring rules) and variable (everything else).
 */
export function monthExpenseComposition(
  entries: LedgerEntry[],
  month: string,
): { fixed: bigint; installments: bigint; variable: bigint } {
  const result = { fixed: 0n, installments: 0n, variable: 0n };
  for (const entry of entries) {
    if (
      entry.type !== 'EXPENSE' ||
      !effective(entry) ||
      competenceMonth(entry) !== month
    ) {
      continue;
    }
    // Installments first: a "parcelado" plan is recurring but not a fixed cost.
    if ((entry.installmentCount ?? 1) > 1) {
      result.installments += entry.amount;
    } else if (entry.recurring) {
      result.fixed += entry.amount;
    } else {
      result.variable += entry.amount;
    }
  }
  return result;
}
